version: '3.7'
services:
  mosquitto:
    image: "eclipse-mosquitto"
    container_name: "mosquitto"
    ports:
      - 2500:1883
      - 9001:9001
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
  sensor-1:
    image: sensor:latest
    restart: on-failure
    depends_on:
      - mosquitto
      - centralstation
    build:
      context: .
      dockerfile: sensorfile
    environment:
      - 'ip=centralStation'
      - 'port=51020'
      - 'sensortype=Fuel_Level'
  sensor-2:
    image: sensor:latest
    restart: on-failure
    depends_on:
      - mosquitto
      - centralstation
    environment:
      - 'ip=centralStation'
      - 'port=51021'
      - 'sensortype=TravelDistance'
  sensor-3:
    image: sensor:latest
    restart: on-failure
    depends_on:
      - mosquitto
      - centralstation
    environment:
      - 'ip=centralStation'
      - 'port=51022'
      - 'sensortype=TrafficState'
  sensor-4:
    image: sensor:latest
    restart: on-failure
    depends_on:
      - mosquitto
      - centralstation
    environment:
      - 'ip=centralStation'
      - 'port=51023'
      - 'sensortype=AvgSpeed'
  sensor-5:
    image: sensor:latest
    restart: on-failure
    depends_on:
      - mosquitto
      - centralstation
    environment:
      - 'ip=centralStation'
      - 'port=51024'
      - 'sensortype=AvgSpeed'
  centralstation:
    build:
      context: .
      dockerfile: centralfile
    environment:
      - 'stationname=Group_e9_Station'
      - 'sensorcount=5'
      - 'sensorstartport=51020'
    depends_on:
      - serviceprovider_1
      - serviceprovider_2
    ports:
      - 8080:8080
      - 51030:51030

  centralstation_2:
    build:
      context: .
      dockerfile: centralfile
    environment:
      - 'stationname=Group_e9_Station'
      - 'sensorcount=5'
      - 'sensorstartport=51020'
    depends_on:
      - serviceprovider_1
      - serviceprovider_2


  serviceprovider_1:
    image: rpc
    restart: always
    depends_on:
      - mosquitto
      - mongo
    build:
      context: .
      dockerfile: serviceproviderfile
    environment:
      - 'ip=centralstation'
      - 'port=56565'
    ports:
      - 9091:9091

  serviceprovider_2:
    image: rpc
    restart: always
    depends_on:
      - mosquitto
      - mongo
    build:
      context: .
      dockerfile: serviceproviderfile
    environment:
      - 'ip=centralstation'
      - 'port=56565'
    ports:
      - 9092:9091
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  mongo-client:
    image: mongo-express:latest
    restart: on-failure
    ports:
      - 8081:8081
    depends_on:
      - mongo
  nginx:
    build:
      context: .
      dockerfile: proxyfile
    ports:
      - "8082:80"
    depends_on:
      - serviceprovider_1
      - serviceprovider_2
