version: '3.7'
services:

  ###########################
  ###### Car 1 ##############
  ###########################

  mosquitto_1:
    image: "eclipse-mosquitto"
    container_name: "mosquitto_1"
  centralstation_1:
    build:
      context: .
      dockerfile: centralfile
    environment:
      - 'stationname=Station1'
      - 'nginxip=nginx'
      - 'nginxport=56565'
      - 'mqttbroker=tcp://mosquitto_1:1883'
      - 'mqtttopic=hda/group_e_9/VS'
    depends_on:
      nginx:
        condition: service_started
      mongo:
        condition: service_healthy
    ports:
      - 8080:8080
  sensor-1:
    restart: on-failure
    build:
      context: .
      dockerfile: sensorfile
    depends_on:
      mongo:
        condition: service_healthy
      mosquitto_1:
        condition: service_started
    environment:
      - 'ip=centralStation'
      - 'port=51021'
      - 'sensortype=TravelDistance'
      - 'mqttbroker=tcp://mosquitto_1:1883'
      - 'mqtttopic=hda/group_e_9/VS'
  sensor-2:
    restart: on-failure
    build:
      context: .
      dockerfile: sensorfile
    depends_on:
      mosquitto_1:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - 'ip=centralStation'
      - 'port=51021'
      - 'sensortype=Fuel_Level'
      - 'mqttbroker=tcp://mosquitto_1:1883'
      - 'mqtttopic=hda/group_e_9/VS'
  sensor-3:
    restart: on-failure
    build:
      context: .
      dockerfile: sensorfile
    depends_on:
      mosquitto_1:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - 'ip=centralStation'
      - 'port=51021'
      - 'sensortype=AvgSpeed'
      - 'mqttbroker=tcp://mosquitto_1:1883'
      - 'mqtttopic=hda/group_e_9/VS'
  sensor-4:
    restart: on-failure
    build:
      context: .
      dockerfile: sensorfile
    depends_on:
      mosquitto_1:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - 'ip=centralStation'
      - 'port=51021'
      - 'sensortype=TrafficState'
      - 'mqttbroker=tcp://mosquitto_1:1883'
      - 'mqtttopic=hda/group_e_9/VS'
  ###########################
  ###### Car 2 ##############
  ###########################
  mosquitto_2:
    image: "eclipse-mosquitto"
    container_name: "mosquitto-2"
  sensor-6:
    restart: on-failure
    build:
      context: .
      dockerfile: sensorfile
    depends_on:
      mosquitto_2:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - 'ip=centralStation'
      - 'port=51021'
      - 'sensortype=Fuel_Level'
      - 'mqttbroker=tcp://mosquitto_2:1883'
      - 'mqtttopic=hda/group_e_9/VS'
  sensor-5:
    restart: on-failure
    build:
      context: .
      dockerfile: sensorfile
    depends_on:
      mosquitto_2:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - 'ip=centralStation'
      - 'port=51021'
      - 'sensortype=TravelDistance'
      - 'mqttbroker=tcp://mosquitto_2:1883'
      - 'mqtttopic=hda/group_e_9/VS'
  sensor-7:
    restart: on-failure
    build:
      context: .
      dockerfile: sensorfile
    depends_on:
      mosquitto_2:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - 'ip=centralStation'
      - 'port=51021'
      - 'sensortype=TrafficState'
      - 'mqttbroker=tcp://mosquitto_2:1883'
      - 'mqtttopic=hda/group_e_9/VS'
  sensor-8:
    restart: on-failure
    build:
      context: .
      dockerfile: sensorfile
    depends_on:
      mosquitto_2:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - 'ip=centralStation'
      - 'port=51021'
      - 'sensortype=AvgSpeed'
      - 'mqttbroker=tcp://mosquitto_2:1883'
      - 'mqtttopic=hda/group_e_9/VS'

  centralstation_2:
    build:
      context: .
      dockerfile: centralfile
    environment:
      - 'stationname=Station2'
      - 'nginxip=nginx'
      - 'nginxport=56565'
      - 'mqttbroker=tcp://mosquitto_2:1883'
      - 'mqtttopic=hda/group_e_9/VS'
    depends_on:
      nginx:
        condition: service_started
      mongo:
        condition: service_healthy
    ports:
      - 8084:8080
  ###########################
  ###### Backend ############
  ###########################
 
  serviceprovider_1:
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: serviceproviderfile
    environment:
      - 'dbip=mongo'
      - 'dbport=27017'
      - 'rpcport=56565'

  serviceprovider_2:
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: serviceproviderfile
    environment:
      - 'dbip=mongo'
      - 'dbport=27017'
      - 'rpcport=56565'

  serviceprovider_3:
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: serviceproviderfile
    environment:
      - 'dbip=mongo'
      - 'dbport=27017'
      - 'rpcport=56565'

  mongo:
    container_name: mongo1
    image: mongo:3.6-jessie
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mongo", "rs.status()"]
      interval: 30s
      timeout: 3s
      start_period: 30s
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    container_name: mongo2
    image: mongo:3.6-jessie
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    container_name: mongo3
    image: mongo:3.6-jessie
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongosetup:
    image: mongo:3.6-jessie
    depends_on:
      - mongo
      - mongo2
      - mongo3
    volumes:
      - .:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]

  mongo-client:
    image: mongo-express:latest
    restart: on-failure
    ports:
      - 8081:8081
    depends_on:
      - mongosetup
  nginx:
    build:
      context: .
      dockerfile: proxyfile
    ports:
      - "8082:80"
    depends_on:
      - serviceprovider_1
      - serviceprovider_2